"""Data models for ROCm FlightDeck."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class Detection:
    """A single detected compatibility issue."""

    id: str
    title: str
    severity: str  # "critical" | "warning" | "info"
    file_path: Optional[str] = None
    evidence: Optional[str] = None
    recommendation: str = ""


@dataclass
class ScanResult:
    """Result of scanning a repository directory."""

    repo_path: str
    files_scanned: List[str] = field(default_factory=list)
    file_contents: Dict[str, str] = field(default_factory=dict)  # rel_path -> text


@dataclass
class ScoreBreakdown:
    """Detailed ROCm Readiness Score breakdown."""

    device_abstraction: int = 0          # max 20
    dependency_compatibility: int = 0    # max 25
    docker_runtime: int = 0              # max 20
    vllm_serving: int = 0                # max 20
    benchmark_readiness: int = 0         # max 15

    deductions: List[str] = field(default_factory=list)
    explanation: str = ""

    @property
    def total_score(self) -> int:
        return (
            self.device_abstraction
            + self.dependency_compatibility
            + self.docker_runtime
            + self.vllm_serving
            + self.benchmark_readiness
        )


@dataclass
class MigrationPlan:
    """Ordered list of migration steps."""

    steps: List[str] = field(default_factory=list)


@dataclass
class GeneratedArtifact:
    """A file generated by the patcher."""

    filename: str
    content: str
    output_path: str


@dataclass
class FlightDeckResult:
    """Top-level result of a full FlightDeck analysis run."""

    repo_path: str
    scan: ScanResult
    detections: List[Detection]
    score: ScoreBreakdown
    plan: MigrationPlan
    artifacts: List[GeneratedArtifact]
    report_path: str = ""
