"""Generate pull request descriptions for ROCm FlightDeck migrations."""

from __future__ import annotations

import re
from pathlib import Path

from core.models import FlightDeckResult
from core.scoring import assessment_label


def generate_pr_description(result: FlightDeckResult, output_base: str) -> str:
    """Write pull_request_description.md to outputs/reports/<repo>/."""
    repo_name = Path(result.repo_path).resolve().name
    safe_name = re.sub(r"[^\w\-.]", "_", repo_name) or "repo"
    out_dir = Path(output_base).resolve() / safe_name
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "pull_request_description.md"
    out_path.write_text(_build_pr_description(result, safe_name), encoding="utf-8")
    return str(out_path)


def _build_pr_description(result: FlightDeckResult, repo_name: str) -> str:
    before = result.before_score or result.score
    after = result.after_score or result.score
    generated = [artifact.filename for artifact in result.artifacts]
    if result.report_path:
        generated.append("migration_report.md")
    generated.append("pull_request_description.md")

    risks = result.remaining_risks or ["Benchmarks not executed in this MVP; validate on AMD Developer Cloud / MI300X."]

    lines = [
        f"# PR: Add ROCm migration starter artifacts for {repo_name}",
        "",
        "## Summary",
        "",
        "This PR adds reviewable ROCm migration starter artifacts generated by ROCm FlightDeck and preserves NVIDIA-specific files as legacy context where applicable.",
        "",
        "## What Changed",
        "",
        "- Added ROCm-first Docker and dependency artifacts.",
        "- Added a ROCm vLLM serving starter.",
        "- Added a benchmark methodology template with no fabricated metrics.",
        "- Added AMD migration notes and a technical migration report.",
        "- Created a migrated repository copy for static review.",
        "",
        "## Why This Matters For AMD ROCm / MI300X",
        "",
        "The changes move CUDA-first assumptions toward a reviewable ROCm workflow for vLLM / PyTorch inference on AMD MI300X while keeping validation explicit and deterministic.",
        "",
        "## Before / After ROCm Readiness Score",
        "",
        f"- Before: {before.total_score}/100 ({assessment_label(before.total_score)})",
        f"- After: {after.total_score}/100 ({assessment_label(after.total_score)})",
        f"- Improvement: {result.improvement_points} point(s)",
        "",
        "## Generated Files",
        "",
    ]
    lines.extend(f"- `{name}`" for name in generated)
    lines.extend([
        "",
        "## Benchmark Status",
        "",
        "Benchmarks not executed in this MVP. Run `benchmark_rocm.py` on AMD Developer Cloud / MI300X to collect real tokens/sec, latency, VRAM usage, cold start time, and test pass rate.",
        "",
        "## Remaining Risks",
        "",
    ])
    lines.extend(f"- {risk}" for risk in risks)
    lines.extend([
        "",
        "## Validation Checklist",
        "",
        "- [ ] Review every generated file and patch hunk.",
        "- [ ] Build `Dockerfile.rocm` on a ROCm-capable machine.",
        "- [ ] Install ROCm PyTorch and ROCm-compatible vLLM dependencies.",
        "- [ ] Run unit and integration tests without executing untrusted code paths.",
        "- [ ] Run `benchmark_rocm.py` on AMD Developer Cloud / MI300X.",
        "- [ ] Record real benchmark metrics in the migration report.",
    ])
    return "\n".join(lines) + "\n"
